/**
 * OpenVibe.Media — service entrypoint (port 4100)
 *
 * Multi-tenant media service: VOD ingest/recording (RTMP pull, RTP, browser
 * chunks), local/B2/R2 storage tiering with presigned-302 playback, clips,
 * pastes, files, thumbnails, and HMAC-signed webhooks. See CONTRACTS.md
 * (Media API v1) and README.md.
 */
'use strict';

// Restore-drill mode (MEDIA_DRILL=1, `ovhost drill media`): refuse an unsafe environment before the
// database is opened, then cut every way out of the process but its own HTTP port. The instance
// serves reads from a restored copy of media.db, never opens a stored file and starts nothing else
// (server/drill.js).
require('dotenv').config();
const drill = require('./drill');
if (drill.enabled) {
    try {
        drill.assertSafe();
    } catch (err) {
        console.error(`[Drill] ${err.message}`);
        process.exit(1);
    }
    drill.installGuards();
    console.log(`[Drill] MEDIA_DRILL: restore-drill instance on ${process.env.HOST}:${process.env.PORT}, database ${require('path').resolve(process.env.DB_PATH)}. Reads only; no stored bytes, background work or outbound connections.`);
}

const fs = require('fs');
const express = require('express');
const config = require('./config');
const db = require('./db/database');
const auth = require('./auth');

// ── Bootstrap ────────────────────────────────────────────────

// A drill creates no storage directory (it writes no file) and seeds nothing: the copy is production's.
if (!drill.enabled) {
    for (const dir of [config.vod.path, config.vod.clipsPath, config.pastes.path, config.thumbnails.path, config.files.path, config.objects.path]) {
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    }
}

db.getDb();          // init schema (WAL)
if (!drill.enabled) {
    auth.seedApps();     // upsert MEDIA_APPS_SEED / MEDIA_APP_KEYS
    auth.ensureTokenOnlyApps();  // tenants reached only with Network service tokens (community)
    auth.startJwksRefresh();     // a drill asks Network for nothing (app keys still verify against the copy)
}

const app = express();
app.set('trust proxy', true);
// Metrics first, so every route below is measured (GET /metrics: loopback callers only).
const release = require('openvibe-shared/release').createRelease({ service: 'media', root: require('path').join(__dirname, '..') });
const observability = require('./observability');
const instrumented = observability.instrument(app, { release: release.release });
// A restore-drill instance answers reads only: 403 for every other method, on every path (before the
// raw-body upload routes below).
if (drill.enabled) app.use(drill.readOnly);
// Object API v2 content uploads read the raw request body, so they sit ahead of the body parsers.
app.put('/api/v2/:app/objects/:id/content', ...require('./objects/routes').contentHandlers);
app.put('/api/v2/:app/objects/:id/multipart/:uploadId/parts/:n', ...require('./objects/routes').partHandlers);
app.use(express.json({ limit: '2mb' }));

// ── Visitor sign-in (OAuth client `media` on the Network; same module as Community/Tools) ──
// Host-only cookies on openvibe.media. No new dependency: cookies are parsed here.
app.use((req, _res, next) => {
    req.cookies = {};
    for (const part of String(req.headers.cookie || '').split(';')) {
        const i = part.indexOf('='); if (i < 1) continue;
        try { req.cookies[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim()); } catch { /* malformed value */ }
    }
    next();
});
{ const legal = require('openvibe-shared/legal'); app.get(legal.PATHS, legal.handler({ id: 'media', service: 'media', host: 'openvibe.media', name: 'OpenVibe.Media', profile: 'hosting' })); app.get('/tos', (_req, res) => res.redirect(301, '/terms')); }
// Brand assets: icon set + web app manifest generated by openvibe-shared/scripts/build-app-icons.js
app.use('/assets', express.static(require('path').join(__dirname, 'brand'), { maxAge: '7d' }));
app.get('/manifest.webmanifest', (_req, res) => res.type('application/manifest+json').sendFile(require('path').join(__dirname, 'brand', 'manifest.webmanifest')));
// ── Internal: avatar ingestion (the Network asks; see server/avatars/ingest.js) ──
{
    const crypto = require('crypto');
    const internalOnly = (req, res, next) => {
        const want = String(config.network.internalApiKey || ''), got = String(req.headers['x-internal-key'] || '');
        const viaProxy = req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || req.headers['cf-connecting-ip'];
        const local = /^(::1|::ffff:127\.|127\.)/.test(String(req.socket.remoteAddress || ''));
        if (viaProxy || !local || want.length < 16 || got.length !== want.length || !crypto.timingSafeEqual(Buffer.from(got), Buffer.from(want))) return res.status(404).json({ error: 'Not found' });
        next();
    };
    const pastes = require('./pastes/routes');
    app.post('/internal/avatar-ingest', internalOnly, require('./avatars/ingest').createIngestHandler({ db: require('./db/database'), config, screenshotsDir: pastes.SCREENSHOTS_DIR, generateSlug: pastes.generateSlug }));
}
const userAuth = require('./user-auth');
const userAuthConfig = {
    baseUrl: config.publicUrl, networkUrl: config.network.url, networkInternalUrl: config.network.internalUrl,
    cookies: { secure: /^https:/.test(config.publicUrl) },
    oauth: { clientId: process.env.OV_OAUTH_CLIENT_ID || 'media', clientSecret: process.env.OV_OAUTH_CLIENT_SECRET || '', redirectUri: process.env.OV_OAUTH_REDIRECT_URI || `${config.publicUrl}/auth/callback` },
};
// A restore drill signs nobody in: that would redeem codes at Network.
if (drill.enabled) app.use('/auth', (req, res) => res.status(503).json({ error: 'This is a restore-drill instance (MEDIA_DRILL): no sign-in', code: 'media.drill_no_sign_in' }));
app.use('/auth', userAuth.createAuthRoutes(userAuthConfig, userAuth.createAuthClient(userAuthConfig)));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));

// CORS preflight for tenant API routes (per-app allow-list; auth-less OPTIONS).
app.options(['/api/v1/:app/*', '/api/v2/:app/*'], (req, res) => {
    const origin = req.headers.origin;
    const appRow = db.getApp(String(req.params.app || ''));
    if (origin && appRow && db.appAllowedOrigins(appRow).includes(origin)) {
        res.set('Access-Control-Allow-Origin', origin);
        res.set('Vary', 'Origin');
        res.set('Access-Control-Allow-Headers', 'Authorization, Content-Type, X-Upload-Token, X-Content-SHA256, Idempotency-Key, traceparent, X-OpenVibe-Request-Id');
        res.set('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    }
    res.sendStatus(204);
});

// ── Routes ───────────────────────────────────────────────────

// What this server runs (ADR-016); the shared navbar's release-watch polls it. POST /release-metrics
// takes open tabs' update reports into /metrics (release_client_updates_total). A restore drill
// answers that POST with the readOnly 403 above, like every other write.
release.mount(app, { registry: instrumented.registry });

app.get('/healthz', (req, res) => {
    res.json({
        ok: true,
        service: 'openvibe-media',
        apps: db.listApps().length,
        recordings: require('./vod/recorder').activeCount(),
        uptime_s: Math.round(process.uptime()),
    });
});

// Readiness: required = database + writable storage; optional (degraded) = Network key, remote tiers, events outbox.
{
    const vodStorageForReady = require('./vod/vod-storage');
    observability.mountReady(app, instrumented.registry, {
        release: release.release, db, config, auth,
        recorder: require('./vod/recorder'),
        events: require('./events'),
        remote: { configured: (n) => vodStorageForReady.providerConfigured(n), probe: (n) => vodStorageForReady.probeProvider(n) },
        drill: drill.enabled,
    });
}

// Per-app media stats (app-key only) — hero/dashboard counters in the owning app.
app.get('/api/v1/:app/stats', auth.tenantAuth(), (req, res) => {
    try {
        res.json(db.getAppStats(req.appId));
    } catch (err) {
        console.error('[Stats] error:', err.message);
        res.status(500).json({ error: 'Failed to compute stats' });
    }
});

// Daily series behind a stat (vods, clips, pastes, hours) — "over time" charts in the owning app.
app.get('/api/v1/:app/stats/series/:metric', auth.tenantAuth(), (req, res) => {
    try {
        const series = db.getAppStatSeries(req.appId, String(req.params.metric), req.query.days);
        if (!series) return res.status(404).json({ error: 'Unknown metric' });
        res.json(series);
    } catch (err) {
        console.error('[Stats] series error:', err.message);
        res.status(500).json({ error: 'Failed to compute series' });
    }
});

try { require('./views/service').ensureSchema(); } catch (e) { console.warn('[Views] schema:', e.message); }
if (!drill.enabled) setInterval(() => { try { const n = require('./views/service').prune(30); if (n) console.log(`[Views] pruned ${n} stale visit row(s)`); } catch { /* */ } }, 12 * 3600 * 1000);
app.use('/api/v1/:app/views', require('./views/routes'));
app.use('/api/v1/:app/vods', require('./vod/routes'));
app.use('/api/v1/:app/clips', require('./vod/clips-routes'));
app.use('/api/v1/:app/pastes', require('./pastes/routes'));
app.use('/api/v1/:app/files', require('./files/routes'));
app.use('/api/v1/:app/thumbnails', require('./thumbnails/routes'));
app.use('/api/v1/:app/assets', require('./assets/routes'));
app.use('/api/v1/:app/admin/storage', require('./admin/routes'));
app.use('/api/v2/:app/objects', require('./objects/routes'));   // canonical object API (docs/object-model.md)
app.use('/api/v2/:app/jobs', require('./jobs/routes'));         // media jobs: thumbnails, split/remux, invariant scans
app.use('/o', require('./objects/routes').publicRouter);        // object bytes (public, or signed)
app.use('/', require('./public/routes'));   // /v /c /p /t /f

// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
    console.error('[HTTP] Unhandled error:', err.message);
    if (!res.headersSent) res.status(err.status || 500).json({ error: err.message || 'Internal error' });
});

// ── Background jobs ──────────────────────────────────────────

const recorder = require('./vod/recorder');
const vodStorage = require('./vod/vod-storage');
const healthJob = require('./vod/health-job');
const thumbService = require('./thumbnails/thumbnail-service');

const timers = [];
function every(ms, fn) {
    const t = setInterval(fn, ms);
    if (t.unref) t.unref();
    timers.push(t);
}

// A restore drill starts none of this: every job below reads or writes stored files, runs ffmpeg,
// talks to B2/R2 or announces outcomes to Live.
if (!drill.enabled) {
    vodStorage.checkProviders()
        .then(() => vodStorage.migrateLegacy().catch(() => {}))
        .catch(err => console.warn('[Boot] Provider check failed:', err.message));
    vodStorage.start();                                        // tiering sweep
    healthJob.start();                                         // health scan + quarantine cleanup
    require('./vod/clip-jobs').start();                        // failed clip re-cuts (auto-retry, hot-fetch)
    require('./objects/verify-job').start();                   // scheduled copy verification (bounded batches; never deletes)
    require('./jobs/worker').start();                          // media_jobs worker (light + heavy lanes; proposals wait for their owner)
    // Descriptor watchdog: a leak here once pinned 80 GB of deleted recordings to the disk.
    every(5 * 60 * 1000, () => {
        try {
            const n = fs.readdirSync('/proc/self/fd').length;
            if (n > 1500) console.warn(`[Boot] ${n} open file descriptors — investigate a stream/handle leak (lsof -p ${process.pid} +L1)`);
        } catch { /* not linux */ }
    });
    every(60 * 1000, () => recorder.checkDisk());              // disk guardian
    every(60 * 60 * 1000, () => thumbService.cleanupOldThumbnails());  // stale live thumbs
    // Object model: purge native objects whose soft-delete retention has passed (held ones are kept).
    every(60 * 60 * 1000, () => {
        try { const n = require('./objects/model').purgeExpired(); if (n) console.log(`[Objects] Purged ${n} expired deleted object(s)`); } catch (err) { console.warn('[Objects] purge:', err.message); }
        // Incomplete multipart uploads past MEDIA_MULTIPART_TTL_HOURS: their parts are deleted (the objects stay uploading).
        try { const r = require('./objects/multipart').purgeExpired(); if (r.expired || r.orphan_dirs) console.log(`[Objects] Multipart: ${r.expired} expired session(s), ${r.orphan_dirs} orphan part dir(s) removed`); } catch (err) { console.warn('[Objects] multipart purge:', err.message); }
    });
    // Project rows that have no media_object yet (first boot after the upgrade: all of them).
    setTimeout(() => {
        try {
            const bf = require('./objects/backfill');
            const r = bf.backfill({ onlyMissing: true });
            if (r.totals.created || r.totals.updated || r.errors.length) console.log(`[Objects] Backfill: ${bf.summarize(r)}`);
        } catch (err) { console.warn('[Objects] Backfill failed:', err.message); }
    }, 15 * 1000).unref?.();

    // Recover from an unclean shutdown: rows stuck in is_recording with no live
    // ffmpeg are finalized from whatever hit the disk.
    setTimeout(() => {
        try {
            const stuck = db.all('SELECT id FROM vods WHERE is_recording = 1');
            for (const row of stuck) {
                if (recorder.isRecording(row.id)) continue;
                console.log(`[Boot] Finalizing orphaned recording vod ${row.id}`);
                require('./vod/finalize').finalizeVod(row.id).catch(() => {});
            }
        } catch (err) {
            console.warn('[Boot] Orphan finalize sweep failed:', err.message);
        }
    }, 5000).unref?.();
}

// ── Listen + graceful shutdown ───────────────────────────────

const server = app.listen(config.port, config.host, () => {
    if (drill.enabled) { console.log(`[Drill] Ready: http://${config.host}:${config.port} (reads only)`); return; }
    console.log(`[Media] OpenVibe.Media listening on ${config.host}:${config.port} (${config.nodeEnv})`);
    console.log(`[Media] Data: db=${config.db.path} vods=${config.vod.path} clips=${config.vod.clipsPath}`);
    console.log(`[Media] RTP ingest pool: udp ${config.rtp.portMin}-${config.rtp.portMax} (127.0.0.1)`);
    // Durable events (roadmap Wave 3): webhook outcomes also go to OpenVibe.Events. Off without EVENTS_URL.
    try { require('./events').init(); } catch (err) { console.warn('[Events] not started:', err.message); }
});

// A drill whose port is taken stops instead of running unready.
if (drill.enabled) server.once('error', (err) => { console.error(`[Drill] HTTP server: ${err.message}`); process.exit(1); });

let shuttingDown = false;
function shutdown(signal) {
    if (shuttingDown) return;
    shuttingDown = true;
    console.log(`[Media] ${signal} received — shutting down`);
    try { recorder.stopAll(); } catch { /* */ }
    try { vodStorage.stop(); } catch { /* */ }
    try { healthJob.stop(); } catch { /* */ }
    try { require('./objects/verify-job').stop(); } catch { /* */ }
    try { require('./jobs/worker').stop(); } catch { /* */ }
    try { auth.stopJwksRefresh(); } catch { /* */ }
    try { require('./events')._reset(); } catch { /* */ }
    for (const t of timers) clearInterval(t);
    server.close(() => {
        try { db.close(); } catch { /* */ }
        process.exit(0);
    });
    // Recordings get STOP_GRACE_MS to flush trailers; don't hang forever.
    setTimeout(() => {
        console.warn('[Media] Forced exit after shutdown grace');
        try { db.close(); } catch { /* */ }
        process.exit(0);
    }, 70_000).unref();
}
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

module.exports = { app, server };
